GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkxOTI3NjMsImV4cCI6MTc0OTE5NjM2M30.FdsNmuAtPGYNKwcm2uqMGtVZD0MdzPKDBbd2RaNvB0s

###
GET http://localhost:5000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzQ4NjkwNjgyLCJleHAiOjE3NDg2OTQyODJ9.mr43GUI6_NArIpeQJghxum1NDFIQL6AKJU5itAhfVO0

###
POST http://localhost:5000/users
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkxOTI3NjMsImV4cCI6MTc0OTE5NjM2M30.FdsNmuAtPGYNKwcm2uqMGtVZD0MdzPKDBbd2RaNvB0s

{
    "nama": "terapis",
    "email": "terapis@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "terapis"
}

###
PATCH http://localhost:5000/users/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkxOTI3NjMsImV4cCI6MTc0OTE5NjM2M30.FdsNmuAtPGYNKwcm2uqMGtVZD0MdzPKDBbd2RaNvB0s

{
    "gambar": "https://res.cloudinary.com/di6b7cor8/image/upload/v1749192225/users/gambar/wgy3rf09kikfvk2dfgph.jpg",  
    "nama": "terapis tiara",
    "email": "terapis@gmail.com",
    "no_telp": "087872721210",
    "bank": "BCA",
    "no_rekening": "534767676",
    "no_telp": "087872721210",
    "alamat": "jalan mawar",
    "jadwalId": 1,
    "password": "123456",
    "confPassword": "123456",
    "role": "terapis",
    "cv_pdf": "https://res.cloudinary.com/di6b7cor8/raw/upload/v1749192226/users/cv/dsub7rqty9vxmjkxn5dc"
}

###
DELETE http://localhost:5000/users/2

//LOGIN
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "terapis@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkxOTI3NjMsImV4cCI6MTc0OTE5NjM2M30.FdsNmuAtPGYNKwcm2uqMGtVZD0MdzPKDBbd2RaNvB0s"

//LOGOUT
###
DELETE http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDg5MzM0MTgsImV4cCI6MTc0ODkzNzAxOH0.B13f1Ns6FH0Pz6OrkvqJ3EIfTQHiCuSHlf66ZVHqxcI

//EDUKASI
###
GET http://localhost:5000/edukasi

###
GET http://localhost:5000/edukasi/2

###
POST http://localhost:5000/edukasi
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NzY1Nzg4LCJleHAiOjE3NDY3NjkzODh9.QW0E3BgV8FPn5xtwZeTgpLL02b6_bem95dupx3RK8U4

{
    "konten": "https://youtu.be/EKEWk4oWmjY?si=cuZdutpYvdmon10B"
}

###
PATCH http://localhost:5000/edukasi/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1ODI3Mzk4LCJleHAiOjE3NDU4MzA5OTh9.ruPa4MuO4sNGg5YhYiim9_-lillb_W6hwg77sh1BqBw

{
    "konten": "https://youtu.be/5Y76XIgwVyI?si=OnoaWp47u1OxUqN8 updated"
}

###
DELETE http://localhost:5000/edukasi/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//JADWAL KEGIATAN
###
GET http://localhost:5000/jadwalKegiatan

###
GET http://localhost:5000/jadwalKegiatan/1

###
POST http://localhost:5000/jadwalKegiatan
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDg3MTMyMDMsImV4cCI6MTc0ODcxNjgwM30.TtAtFDKE--A5N1TGRS1Jjts7H7Mdx7nmt6ECcuhCa5E

{
    "tanggal_waktu": "2025-10-12T15:00:00+07:00",
    "jenis_kegiatan": "Baksos",
    "lokasi": "Jl Mawar",
    "deskripsi": "bakti sosial di lingkungan jalan mawar"
}

###
PATCH http://localhost:5000/jadwalKegiatan/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

{
    "tanggal_waktu": "2025-10-12T15:00:00+07:00",
    "jenis_kegiatan": "Baksos",
    "lokasi": "Jl Mawar updated",
    "deskripsi": "bakti sosial di lingkungan jalan mawar"
}

###
DELETE http://localhost:5000/jadwalKegiatan/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//TERAPIS KAMI
###
GET http://localhost:5000/terapis
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1ODI3Mzk4LCJleHAiOjE3NDU4MzA5OTh9.ruPa4MuO4sNGg5YhYiim9_-lillb_W6hwg77sh1BqBw

###
GET http://localhost:5000/terapis/1

###
POST http://localhost:5000/terapis
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NDAxNjkxLCJleHAiOjE3NDc0MDUyOTF9.xHfhxkibBbGzyHkV4XZ2aBy6Yuf8Z86gM_LN72X4Eks

        {
          "gambar": "https://example.com/terapis1.jpg",
          "nama": "Dr. Tiara Nisa",
          "alamat": "Jl. Sehat No. 5, Jakarta",
          "jadwal": "Senin, 09:00-17:00"
        }

###
PATCH http://localhost:5000/terapis/2
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NDAxNjkxLCJleHAiOjE3NDc0MDUyOTF9.xHfhxkibBbGzyHkV4XZ2aBy6Yuf8Z86gM_LN72X4Eks

        {
          "gambar": "https://example.com/terapis1.jpg",
          "nama": "Dr. Tiara Nisa",
          "no_telp": "08755656565",
          "no_rekening": "5787736",
          "alamat": "Jl. Sehat No. 5, Jakarta",
          "jadwal": "Senin:09:00-17:00"
        }

###
DELETE http://localhost:5000/terapis/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//DOKUMENTASI
###
GET http://localhost:5000/dokumentasi

###
GET http://localhost:5000/dokumentasi/1

###
POST http://localhost:5000/dokumentasi
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

        {
          "gambar": "https://example.com/dokumentasi1.jpg",
          "judul": "Baksos"
        }

###
PATCH http://localhost:5000/dokumentasi/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

        {
          "gambar": "https://example.com/dokumentasi1.jpg",
          "judul": "Baksos Updated"
        }

###
DELETE http://localhost:5000/dokumentasi/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw

//TESTIMONI
###
GET http://localhost:5000/testimoni

###
GET http://localhost:5000/testimoni/1

###
POST http://localhost:5000/testimoni
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NDE1NjM4LCJleHAiOjE3NDc0MTkyMzh9.9SHLkH04VruqjAQsl2MgKWGxn1LqQ-ToRHJ6qOpMamE

        {
          "media": "https://res.cloudinary.com/di6b7cor8/image/upload/v1747414825/reservasi/dmyvi47ikouwk30gb8r6.jpg"
        }

###
PATCH http://localhost:5000/testimoni/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NDE1NjM4LCJleHAiOjE3NDc0MTkyMzh9.9SHLkH04VruqjAQsl2MgKWGxn1LqQ-ToRHJ6qOpMamE

        {
          "media": "https://res.cloudinary.com/di6b7cor8/image/upload/v1747414825/reservasi/dmyvi47ikouwk30gb8r6.jpg"
        }

###
DELETE http://localhost:5000/testimoni/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//PERTANYAAN
###
GET http://localhost:5000/pertanyaan

###
GET http://localhost:5000/pertanyaan/1

###
POST http://localhost:5000/pertanyaan
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDg3MTMyMDMsImV4cCI6MTc0ODcxNjgwM30.TtAtFDKE--A5N1TGRS1Jjts7H7Mdx7nmt6ECcuhCa5E

        {
          "judul_pertanyaan": "Efek Paska Terapi",
          "isi_pertanyaan": "Pegal, rasa memar di titik bekas totok, Kadang demam panas dingin, Terasa gatal di punggung, dan Detosifikasi: Buang Air Kecil, BAB, Buang Gas, Mual, muntah, berkeringat, atau keluar butiran seperti pasir dari pori2 kulit."
        }

###
PATCH http://localhost:5000/pertanyaan/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2OTc5ODk4LCJleHAiOjE3NDY5ODM0OTh9.ygNuz2Efz0JMwlF8ClwJArTPRhGjn_ZMfbBUH6euNQI

        {
          "judul_pertanyaan": "Manfaat",
          "isi_pertanyaan": "Menyembuhkan Penyakit Updated jdhjbfjksbcjkjlkadnkanskladduadtsufgccjd jc sdklncsandslkdnksladkslahcsc kdlnckflndc"
        }

###
DELETE http://localhost:5000/pertanyaan/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//TINJAUAN
###
GET http://localhost:5000/tinjauan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2OTUwNjAwLCJleHAiOjE3NDY5NTQyMDB9.RpU9neLytPkfX-L19uumsM69QsyneIUyuI2Jbx04dmQ

###
GET http://localhost:5000/tinjauan/1

###
POST http://localhost:5000/tinjauan
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgzNTkxLCJleHAiOjE3NDU1ODcxOTF9.hwJKCpb9LhnmNsr0Xry-RSRhyi-d5PsTfHaPw0E-Rkk

{
    "nama": "anonim",
    "layanan": "Edukasi",
    "rating": 5,
    "tinjauan": "Edukasi sangat membantu!"
}

###
PATCH http://localhost:5000/tinjauan/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

{
    "nama": "anonymous",
    "layanan": "Edukasi",
    "rating": 5,
    "tinjauan": "Edukasi sangat membantu!"
}

###
DELETE http://localhost:5000/tinjauan/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//PERTANYAAN
###
GET http://localhost:5000/pertanyaan

###
GET http://localhost:5000/pertanyaan/1

###
POST http://localhost:5000/pertanyaan
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

        {
          "judul_pertanyaan": "Manfaat",
          "isi_pertanyaan": "Menyembuhkan Penyakit"
        }

###
PATCH http://localhost:5000/pertanyaan/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NTgwMDUxLCJleHAiOjE3NDU1ODM2NTF9.F4m6TTIC8k92kvb8tmCIf0KZLWwFm27QSsUX479Y_1c

        {
          "judul_pertanyaan": "Manfaat",
          "isi_pertanyaan": "Menyembuhkan Penyakit Updated"
        }

###
DELETE http://localhost:5000/pertanyaan/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU2MzY5NywiZXhwIjoxNzQ1NTY3Mjk3fQ.WsWWVUJtnx9DVDGeJmM3H9ib0Z0w_PnrPjlyqjpoFQw


//RESERVASI
###
GET http://localhost:5000/reservasi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDg5MzM0MTgsImV4cCI6MTc0ODkzNzAxOH0.B13f1Ns6FH0Pz6OrkvqJ3EIfTQHiCuSHlf66ZVHqxcI

###
GET http://localhost:5000/reservasi/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDg3MTY4NTIsImV4cCI6MTc0ODcyMDQ1Mn0.KEtZuMVrv4Qclvs-yGM-f32MnTKAGxbfNR_3Briz6Uc

###
POST http://localhost:5000/reservasi
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDkzNzU5LCJleHAiOjE3NDg0OTczNTl9.JDdkhfO2VkC1LeHayoR-Ggn67t73GP_qFGWDzPANr1I

{
    "layanan": "Datang Langsung",
    "userId": 1,
    "jadwalId": 2,
    "tanggal_waktu": "2025-10-12T15:00:00+07:00",
    "nama": "tiara",
    "usia": 21,
    "no_telp": "08775757575",
    "alamat": "alamat",
    "keluhan": "sakit punggung",
    "pembayaran": "Tunai",
    "bukti_pembayaran": "",
    "status": "pending"
}

###
PATCH http://localhost:5000/reservasi/47
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDkzNzU5LCJleHAiOjE3NDg0OTczNTl9.JDdkhfO2VkC1LeHayoR-Ggn67t73GP_qFGWDzPANr1I

{
    "layanan": "Datang Langsung",
    "userId": 1,
    "jadwalId": 2,
    "tanggal_waktu": "2025-10-12T15:00:00+07:00",
    "nama": "tiara updated",
    "usia": 21,
    "no_telp": "08775757575",
    "alamat": "alamat",
    "keluhan": "sakit punggung",
    "pembayaran": "transfer",
    "bukti_pembayaran": "https://res.cloudinary.com/di6b7cor8/image/upload/v1748359947/reservasi/fahtvybv5510yvjmkzxk.jpg",
    "status": "pending"
}

###
DELETE http://localhost:5000/reservasi/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NDE0OTE0LCJleHAiOjE3NDc0MTg1MTR9.98W6aVgkozPA0CJ8ndLtrtVp-YDFLZ_b-J_WO262RRk


//JADWAL TERAPIS
###
GET http://localhost:5000/jadwalTerapis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkyNjI4MDQsImV4cCI6MTc0OTI2NjQwNH0.5caTYYSYOX5yLOYuA1zpRahzUiO_IrcSZ5Ljb7pzOFI

###
GET http://localhost:5000/jadwalTerapis/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzQ5MjI5MDQ3LCJleHAiOjE3NDkyMzI2NDd9.n0RzxTIWGKC4EJ3Zt540BDEyTvnR72YBdpm-eEO6zYI

###
GET http://localhost:5000/jadwalTerapis/16/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkyNjI4MDQsImV4cCI6MTc0OTI2NjQwNH0.5caTYYSYOX5yLOYuA1zpRahzUiO_IrcSZ5Ljb7pzOFI

###
POST http://localhost:5000/jadwalTerapis
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlcmFwaXMiLCJpYXQiOjE3NDkxMTQ2MDcsImV4cCI6MTc0OTExODIwN30.ONLUgZaYPbDNA4oYz_eX78ANFVwoOFzz5GHXa04MP7E

{
    "userId": 1,
    "hari":  "Kamis",
    "jam": "13.00 - 15.00"
}

###
PATCH http://localhost:5000/jadwalTerapis/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzQ5MjIxNjAwLCJleHAiOjE3NDkyMjUyMDB9.ADYh96vIvFYMk5kT3cdNxVGzcOAFbiysZzmF3TCZJI4

{

    "userId": 1,
    "hari":  "Senin updated",
    "jam": "13.00 - 15.00"

}

###
DELETE http://localhost:5000/jadwalTerapis/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDkzNzU5LCJleHAiOjE3NDg0OTczNTl9.JDdkhfO2VkC1LeHayoR-Ggn67t73GP_qFGWDzPANr1I


